# production profile
spring:
  config:
    activate:
      on-profile: prod
  name: EVA-Server-PROD
  environment: production
  enabled: false
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    datasource:
      url: "jdbc:postgresql://localhost:5432/postgres"
      username: ${EVA_DB_USER}
      password: ${EVA_DB_PASSWORD}